# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.


## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [2]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [11]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix

In [23]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9164, 0.6477, 0.0278],
        [0.6899, 0.0216, 0.3003],
        [0.2523, 0.0653, 0.5908],
        [0.7984, 0.9727, 0.4287],
        [0.6653, 0.6545, 0.7461]])


Get its size

In [20]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [26]:
x = torch.rand(5, 3)
x[0][1:] = 2
print(x)

tensor([[0.2922, 2.0000, 2.0000],
        [0.2782, 0.6816, 0.6901],
        [0.6702, 0.9468, 0.0773],
        [0.3554, 0.6924, 0.9087],
        [0.1571, 0.6520, 0.6378]])


## Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [55]:
t = torch.empty(2, 17, dtype=torch.int)
print(t)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
       dtype=torch.int32)


In [56]:
t1 = torch.empty(3, 1, dtype=torch.float)
print(t1)

t2 = torch.FloatTensor(3, 1)
print(t2)

tensor([[0.],
        [0.],
        [0.]])
tensor([[0.],
        [0.],
        [0.]])


In [57]:
t = torch.LongTensor(5, 2, 1)

t.fill_(7)

t = torch.fill(t, 5)

t[:] = 9

print(t)

tensor([[[9],
         [9]],

        [[9],
         [9]],

        [[9],
         [9]],

        [[9],
         [9]],

        [[9],
         [9]]])


In [58]:
t = torch.tensor([0 for _ in range(5)], dtype=torch.uint8)

t[1:4] = 1
print(t)

tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [79]:
x = torch.full((5, 3), 1, dtype=torch.float)
y = torch.rand(5, 3)

print(x)
print(y)
print(x + y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.4974, 0.5686, 0.5973],
        [0.9716, 0.5943, 0.3213],
        [0.9366, 0.2502, 0.2641],
        [0.5417, 0.6688, 0.1753],
        [0.1803, 0.1161, 0.9382]])
tensor([[1.4974, 1.5686, 1.5973],
        [1.9716, 1.5943, 1.3213],
        [1.9366, 1.2502, 1.2641],
        [1.5417, 1.6688, 1.1753],
        [1.1803, 1.1161, 1.9382]])


### 2.2 Addition: syntax 2

In [80]:
print(torch.add(x, y))

print(x.add_(y))
print(x)

tensor([[1.4974, 1.5686, 1.5973],
        [1.9716, 1.5943, 1.3213],
        [1.9366, 1.2502, 1.2641],
        [1.5417, 1.6688, 1.1753],
        [1.1803, 1.1161, 1.9382]])
tensor([[1.4974, 1.5686, 1.5973],
        [1.9716, 1.5943, 1.3213],
        [1.9366, 1.2502, 1.2641],
        [1.5417, 1.6688, 1.1753],
        [1.1803, 1.1161, 1.9382]])
tensor([[1.4974, 1.5686, 1.5973],
        [1.9716, 1.5943, 1.3213],
        [1.9366, 1.2502, 1.2641],
        [1.5417, 1.6688, 1.1753],
        [1.1803, 1.1161, 1.9382]])


### 2.3 Addition: giving an output tensor

In [81]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.9947, 2.1371, 2.1946],
        [2.9432, 2.1885, 1.6425],
        [2.8731, 1.5005, 1.5283],
        [2.0834, 2.3375, 1.3505],
        [1.3605, 1.2322, 2.8763]])


### 2.4 Addition: in-place

adds `x` to `y`

In [62]:
y.add_(x)
print(y)

tensor([[0.7194, 2.9203, 2.3590],
        [1.1464, 1.1307, 0.7276],
        [1.5313, 1.0233, 0.5055],
        [1.2258, 1.5444, 1.7984],
        [0.3300, 0.7923, 1.3269]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [82]:
print(x[:, 1])

tensor([1.5686, 1.5943, 1.2502, 1.6688, 1.1161])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [ ]:
x = torch.tensor([[i * 5 + j for j in range(5)] for i in range(1)])
print(x)

y = torch.tensor([[i+1] for i in range(5)])
print(y)

print(x * y)
res = torch.empty(5, 5)
print(torch.mul(x, y, out=res))

tensor([[0, 1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
tensor([[ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8],
        [ 0,  3,  6,  9, 12],
        [ 0,  4,  8, 12, 16],
        [ 0,  5, 10, 15, 20]])
tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 0.,  2.,  4.,  6.,  8.],
        [ 0.,  3.,  6.,  9., 12.],
        [ 0.,  4.,  8., 12., 16.],
        [ 0.,  5., 10., 15., 20.]])


In [121]:
x = torch.tensor([[i * 4 + j for j in range(4)] for i in range(2)])
print(x)

y = torch.tensor([[i * 2 + j for j in range(2)] for i in range(4)])
print(y)

print(torch.matmul(x, y))
print(x.matmul(y))

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])
tensor([[28, 34],
        [76, 98]])
tensor([[28, 34],
        [76, 98]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [135]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [136]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [137]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [141]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [144]:
t = torch.ones(5, 2)
print(t)

t = t.numpy()
print(t)

t = torch.from_numpy(t)
print(t)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [145]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
